### PR TITLE
update to v0.5.1

### PR DESCRIPTION
**Pull request by Bnyro**

### CODE REVIEW

**Comment by shellheim** [comment]
Is it the `&` instead of `&amp;` [here?](https://github.com/lemmygtk/lemoa/blob/main/data/io.github.lemmygtk.lemoa.metainfo.xml.in#L40)

**Comment by Bnyro** [comment]
Oh yes, that makes sense. I will retry it in a sec, thank you!

**Comment by Bnyro** [comment]
bot, build

**Comment by shellheim** [comment]
Welp, the app runs but logging on my instance gives the error `error decoding reponse body: input is not enough for unique date and time at line 1 column 340`

**Pull request merged**
